In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Intro to Tensors

# Creating Tensors

In [ ]:
# Scalar Tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# 0 dimensional Tensor (Scalar)
scalar.ndim

0

In [ ]:
# Get the tensor back as Python integer
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])

In [ ]:
# Vector has 1 dimension
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[13,14],
                      [19,56]])
MATRIX

tensor([[13, 14],
        [19, 56]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.Tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors

Why random Tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers - look at data - update random numbers - look at data - update random numbers`

In [ ]:
# Make a tensor with random data
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3500, 0.6649, 0.7966, 0.4657],
        [0.8238, 0.7444, 0.6533, 0.3611],
        [0.3058, 0.6519, 0.0166, 0.3667]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create random tensor with similar shape to an image tensor
random_img_size_tensor = torch.rand(size=(224,224,3))
random_img_size_tensor

tensor([[[0.3831, 0.5560, 0.3492],
         [0.8292, 0.4208, 0.8741],
         [0.9676, 0.8319, 0.0411],
         ...,
         [0.2974, 0.6495, 0.4734],
         [0.5188, 0.2926, 0.9281],
         [0.4367, 0.8672, 0.1768]],

        [[0.0096, 0.2811, 0.2828],
         [0.8710, 0.5747, 0.4747],
         [0.3281, 0.8904, 0.0388],
         ...,
         [0.5292, 0.6168, 0.1670],
         [0.7998, 0.7125, 0.8592],
         [0.9102, 0.7811, 0.5501]],

        [[0.2858, 0.0605, 0.1457],
         [0.5386, 0.8261, 0.3718],
         [0.6723, 0.5829, 0.4712],
         ...,
         [0.4394, 0.5584, 0.0438],
         [0.9989, 0.7261, 0.1383],
         [0.4564, 0.7003, 0.4822]],

        ...,

        [[0.7234, 0.1570, 0.5753],
         [0.4127, 0.9287, 0.3408],
         [0.3762, 0.5214, 0.4464],
         ...,
         [0.5104, 0.8147, 0.4062],
         [0.6962, 0.8578, 0.6148],
         [0.9689, 0.7222, 0.8915]],

        [[0.9154, 0.4126, 0.1012],
         [0.0653, 0.6726, 0.0776],
         [0.

In [ ]:
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_test_tensor = torch.rand((68,587,3))
random_test_tensor

tensor([[[0.4805, 0.0981, 0.1177],
         [0.6501, 0.9978, 0.3712],
         [0.8886, 0.3317, 0.8501],
         ...,
         [0.3456, 0.4638, 0.2905],
         [0.5368, 0.4259, 0.8810],
         [0.7651, 0.9027, 0.9526]],

        [[0.4651, 0.9824, 0.6956],
         [0.6755, 0.2839, 0.1793],
         [0.5479, 0.8248, 0.9366],
         ...,
         [0.0130, 0.1943, 0.6834],
         [0.8193, 0.8898, 0.1867],
         [0.7805, 0.9907, 0.5482]],

        [[0.9815, 0.5164, 0.2049],
         [0.3646, 0.2771, 0.3222],
         [0.9551, 0.9704, 0.0606],
         ...,
         [0.5733, 0.9578, 0.3574],
         [0.2094, 0.6320, 0.6076],
         [0.8160, 0.9383, 0.1222]],

        ...,

        [[0.9827, 0.3760, 0.7078],
         [0.6671, 0.6070, 0.9072],
         [0.8337, 0.7130, 0.3887],
         ...,
         [0.3584, 0.2361, 0.7456],
         [0.1566, 0.3560, 0.7230],
         [0.7933, 0.9106, 0.8262]],

        [[0.4077, 0.8829, 0.0842],
         [0.3079, 0.7238, 0.1585],
         [0.

## Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create tensor of ones
ones = torch.ones(size=(5,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

### Create a range of tensors and tensors-like


In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(0,11)

In [ ]:
torch.__version__

'2.1.0+cu121'

In [ ]:
ten_zeros = torch.zeros_like(one_to_ten)

In [ ]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and Deep Learning
1. Tensors are not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16, # What datatypes are available for tensors
                               device='cpu', # What device is the tensor running on
                               requires_grad=False) # Tells whether the tensor should track the gradient through calculations
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting info from tensors

1. Tensors are not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from tensor, use `tensor.device`

In [ ]:
# Create a random tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7205, 0.3517, 0.0785, 0.8485],
        [0.0013, 0.9679, 0.9837, 0.1239],
        [0.4887, 0.0128, 0.0787, 0.1829]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.7205, 0.3517, 0.0785, 0.8485],
        [0.0013, 0.9679, 0.9837, 0.1239],
        [0.4887, 0.0128, 0.0787, 0.1829]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operation include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Mult tensor by 10
tensor = tensor *10
tensor

tensor([10, 20, 30])

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
tensor -10

tensor([ 0, 10, 20])

In [ ]:
# Pytorch in-built functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [ ]:
torch.add(tensor,10)

tensor([20, 30, 40])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - mathisfun matrix-multiplying

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3,2)` won't work
* `(2, 3) @ (3,2)` will work
* `(3, 2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> (2,2)
* `(3, 2) @ (2, 3)` -> (3,3)

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.7807, 0.8852, 1.0930],
        [0.2752, 0.3449, 0.3822],
        [0.4421, 0.2097, 0.6454]])

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.1266, 0.3999],
        [0.7019, 0.3693]])

In [ ]:
torch.rand(2,3), torch.rand(3,2)

(tensor([[0.1282, 0.2689, 0.9146],
         [0.2686, 0.8490, 0.5347]]),
 tensor([[0.0672, 0.7477],
         [0.8209, 0.2777],
         [0.8144, 0.2168]]))

In [ ]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [ ]:
# Matrix (in this case it's a vector, but the general rules still apply) multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [ ]:
# Matrix multiplication by hand
10**2 + 20**2 + 30**2

1400

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]**2
value


CPU times: user 919 µs, sys: 0 ns, total: 919 µs
Wall time: 1.08 ms


tensor(1400)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 159 µs, sys: 0 ns, total: 159 µs
Wall time: 165 µs


tensor(1400)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (its just an alias for writing less code)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# x = x.type(torch.float32)

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

### Finding the positional min and max

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
y = torch.tensor([1,2,39,9,1,6])
y.argmax()

tensor(2)

In [ ]:
y.argmin()

tensor(0)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensors on top of each other(vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(0., 40.)
x, x.shape

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
         28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.]),
 torch.Size([40]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(2, 2, 2, 5)
x_reshaped, x_reshaped.shape

(tensor([[[[ 0.,  1.,  2.,  3.,  4.],
           [ 5.,  6.,  7.,  8.,  9.]],
 
          [[10., 11., 12., 13., 14.],
           [15., 16., 17., 18., 19.]]],
 
 
         [[[20., 21., 22., 23., 24.],
           [25., 26., 27., 28., 29.]],
 
          [[30., 31., 32., 33., 34.],
           [35., 36., 37., 38., 39.]]]]),
 torch.Size([2, 2, 2, 5]))

In [ ]:
# Change the view
z = x.view(8,5)
z, z.shape

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34.],
         [35., 36., 37., 38., 39.]]),
 torch.Size([8, 5]))

In [ ]:
x, z

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
         28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.]),
 tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34.],
         [35., 36., 37., 38., 39.]]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
x, z

(tensor([ 5.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.,  5., 11., 12., 13.,
         14.,  5., 16., 17., 18., 19.,  5., 21., 22., 23., 24.,  5., 26., 27.,
         28., 29.,  5., 31., 32., 33., 34.,  5., 36., 37., 38., 39.]),
 tensor([[ 5.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [ 5., 11., 12., 13., 14.],
         [ 5., 16., 17., 18., 19.],
         [ 5., 21., 22., 23., 24.],
         [ 5., 26., 27., 28., 29.],
         [ 5., 31., 32., 33., 34.],
         [ 5., 36., 37., 38., 39.]]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.hstack([x,x,x,x])
x_stacked, x_stacked.shape

(tensor([ 5.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.,  5., 11., 12., 13.,
         14.,  5., 16., 17., 18., 19.,  5., 21., 22., 23., 24.,  5., 26., 27.,
         28., 29.,  5., 31., 32., 33., 34.,  5., 36., 37., 38., 39.,  5.,  1.,
          2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.,  5., 11., 12., 13., 14.,  5.,
         16., 17., 18., 19.,  5., 21., 22., 23., 24.,  5., 26., 27., 28., 29.,
          5., 31., 32., 33., 34.,  5., 36., 37., 38., 39.,  5.,  1.,  2.,  3.,
          4.,  5.,  6.,  7.,  8.,  9.,  5., 11., 12., 13., 14.,  5., 16., 17.,
         18., 19.,  5., 21., 22., 23., 24.,  5., 26., 27., 28., 29.,  5., 31.,
         32., 33., 34.,  5., 36., 37., 38., 39.,  5.,  1.,  2.,  3.,  4.,  5.,
          6.,  7.,  8.,  9.,  5., 11., 12., 13., 14.,  5., 16., 17., 18., 19.,
          5., 21., 22., 23., 24.,  5., 26., 27., 28., 29.,  5., 31., 32., 33.,
         34.,  5., 36., 37., 38., 39.]),
 torch.Size([160]))

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped

tensor([[[[ 5.,  1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.,  9.]],

         [[ 5., 11., 12., 13., 14.],
          [ 5., 16., 17., 18., 19.]]],


        [[[ 5., 21., 22., 23., 24.],
          [ 5., 26., 27., 28., 29.]],

         [[ 5., 31., 32., 33., 34.],
          [ 5., 36., 37., 38., 39.]]]])

In [ ]:
x = torch.arange(0., 9.)

In [ ]:
x[0] = 5

In [ ]:
x

tensor([5., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x.shape

torch.Size([9])

In [ ]:
x_reshape = x.reshape(1,9)

In [ ]:
x_reshape, x_reshape.shape

(tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 9]))

In [ ]:
x_reshape.squeeze_()

tensor([5., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x_reshape.shape

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds single dim to a target tensor at a specific dim (dimension)

In [ ]:
print(f'previous target: {x_reshape}')
print(f'\nprevious shape: {x_reshape.shape}')

# Add an extra dimension with unsqueeze
x_unsqueezed = x_reshape.unsqueeze(dim=0)
print(f'\nNew Tensor: {x_unsqueezed}')
print(f'\nNew shape: {x_unsqueezed.shape}')

previous target: tensor([5., 1., 2., 3., 4., 5., 6., 7., 8.])

previous shape: torch.Size([9])

New Tensor: tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8.]])

New shape: torch.Size([1, 9])


In [ ]:
 # torch.permute() - rearranges the dimensions of a target tensor in a specified order
 x_original = torch.rand(size=(224,224, 3)) # H, W, C

 # Permute the original tensor to rearrange the axis (or dim) order
 x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0->1, 1->2, 2->0

In [ ]:
x_permuted, x_original, x_permuted.shape, x_original.shape

(tensor([[[0.1184, 0.2002, 0.9433,  ..., 0.1793, 0.9734, 0.0577],
          [0.6789, 0.4094, 0.4215,  ..., 0.4696, 0.1920, 0.5446],
          [0.2265, 0.6312, 0.8978,  ..., 0.1078, 0.1465, 0.0419],
          ...,
          [0.9010, 0.9660, 0.6830,  ..., 0.7720, 0.3307, 0.4985],
          [0.1323, 0.8274, 0.8516,  ..., 0.0374, 0.2513, 0.6367],
          [0.4348, 0.6002, 0.7294,  ..., 0.2642, 0.3936, 0.8184]],
 
         [[0.2052, 0.0556, 0.3428,  ..., 0.3001, 0.0608, 0.6785],
          [0.5224, 0.2743, 0.2061,  ..., 0.8429, 0.4682, 0.4494],
          [0.3227, 0.1060, 0.8861,  ..., 0.9776, 0.1328, 0.8046],
          ...,
          [0.7235, 0.2722, 0.3220,  ..., 0.4466, 0.9241, 0.3225],
          [0.9269, 0.2863, 0.5028,  ..., 0.9385, 0.2719, 0.7442],
          [0.7640, 0.9199, 0.0473,  ..., 0.5292, 0.3587, 0.4554]],
 
         [[0.4381, 0.3095, 0.3833,  ..., 0.1496, 0.0397, 0.3835],
          [0.0779, 0.0037, 0.1473,  ..., 0.3463, 0.7921, 0.7946],
          [0.1910, 0.3435, 0.8842,  ...,

In [ ]:
x_permuted[:, :, 0] = 1
x_permuted, x_original

(tensor([[[1.0000, 0.2002, 0.9433,  ..., 0.1793, 0.9734, 0.0577],
          [1.0000, 0.4094, 0.4215,  ..., 0.4696, 0.1920, 0.5446],
          [1.0000, 0.6312, 0.8978,  ..., 0.1078, 0.1465, 0.0419],
          ...,
          [1.0000, 0.9660, 0.6830,  ..., 0.7720, 0.3307, 0.4985],
          [1.0000, 0.8274, 0.8516,  ..., 0.0374, 0.2513, 0.6367],
          [1.0000, 0.6002, 0.7294,  ..., 0.2642, 0.3936, 0.8184]],
 
         [[1.0000, 0.0556, 0.3428,  ..., 0.3001, 0.0608, 0.6785],
          [1.0000, 0.2743, 0.2061,  ..., 0.8429, 0.4682, 0.4494],
          [1.0000, 0.1060, 0.8861,  ..., 0.9776, 0.1328, 0.8046],
          ...,
          [1.0000, 0.2722, 0.3220,  ..., 0.4466, 0.9241, 0.3225],
          [1.0000, 0.2863, 0.5028,  ..., 0.9385, 0.2719, 0.7442],
          [1.0000, 0.9199, 0.0473,  ..., 0.5292, 0.3587, 0.4554]],
 
         [[1.0000, 0.3095, 0.3833,  ..., 0.1496, 0.0397, 0.3835],
          [1.0000, 0.0037, 0.1473,  ..., 0.3463, 0.7921, 0.7946],
          [1.0000, 0.3435, 0.8842,  ...,

In [ ]:
x_original[:, :, 0] = 0
x_permuted, x_original

(tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
 
         [[1.0000, 0.0556, 0.3428,  ..., 0.3001, 0.0608, 0.6785],
          [1.0000, 0.2743, 0.2061,  ..., 0.8429, 0.4682, 0.4494],
          [1.0000, 0.1060, 0.8861,  ..., 0.9776, 0.1328, 0.8046],
          ...,
          [1.0000, 0.2722, 0.3220,  ..., 0.4466, 0.9241, 0.3225],
          [1.0000, 0.2863, 0.5028,  ..., 0.9385, 0.2719, 0.7442],
          [1.0000, 0.9199, 0.0473,  ..., 0.5292, 0.3587, 0.4554]],
 
         [[1.0000, 0.3095, 0.3833,  ..., 0.1496, 0.0397, 0.3835],
          [1.0000, 0.0037, 0.1473,  ..., 0.3463, 0.7921, 0.7946],
          [1.0000, 0.3435, 0.8842,  ...,

### Indexing (selecting data from tensors)

indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 10.).reshape(1,3,3)
x, x.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0, 0, 2]

tensor(3.)

In [ ]:
x[0], x[0, 0], x[0, 0, 0]

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([1., 2., 3.]),
 tensor(1.))

In [ ]:
x[:, -1]

tensor([[7., 8., 9.]])

In [ ]:
gh = torch.randn(3,3,3)

In [ ]:
gh

tensor([[[-1.8023,  0.3577, -0.0428],
         [ 1.0715, -0.6753,  0.3381],
         [ 0.4486,  0.6700, -1.0773]],

        [[-3.4112,  0.0358,  0.8539],
         [ 0.4186,  0.2325, -0.5761],
         [ 0.0286, -0.0085, -0.6641]],

        [[ 0.1323,  0.7772, -0.7666],
         [-0.2313, -1.0537,  0.0527],
         [ 2.2188,  1.0865, -1.0211]]])

In [ ]:
gh[:, -1]

tensor([[ 0.4486,  0.6700, -1.0773],
        [ 0.0286, -0.0085, -0.6641],
        [ 2.2188,  1.0865, -1.0211]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2., 5., 8.]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5.])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1., 2., 3.])

In [ ]:
# INdex on x to return 9
print(x[0,2,2])
# iNdex on x to retunr 3,6,9
print(x[:, :, 2])

tensor(9.)
tensor([[3., 6., 9.]])


In [ ]:
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype # Remember that when converting from numpy array to tensor, dtype will be float64 by default, so change the dtype when converting

torch.float64

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better represenations of the data -> again -> again -> again`

To reduce randomness in neural networks and PyTOrch comes the concept of a random seed.

Essentially wha tthe random seed is "flavour" the randomness



In [ ]:

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0596, 0.6276, 0.9205, 0.7128],
        [0.6896, 0.1716, 0.8382, 0.4655],
        [0.4798, 0.9803, 0.7281, 0.4093]])
tensor([[0.9889, 0.8306, 0.7486, 0.1431],
        [0.2525, 0.1399, 0.8055, 0.4203],
        [0.3183, 0.0513, 0.3939, 0.5265]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good

### 1. Getting a GPU

1. Easiest - Use google colab for a free
2. Use your own GPU. There are lots of options, but they can be pretty pricy and need some setup
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation:

In [ ]:
### 2. Check for GPU access with PyTorch

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
torch.cuda.is_available()

False

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [ ]:
torch.cuda.device_count()

0

### 3. Putting tensors (and models) on teh GPU
GPUs are fsater than cpus!

In [ ]:
torch = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1., 1., 1., 1., 1., 1., 1.]) cpu


In [ ]:
# Move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cpu')

### 4. Move tensors back to cpu

In [ ]:
# If tensor on gpu, cant transform to numpy. Since the gpu is not available, the below code works
tensor_on_gpu.numpy()

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)